
export enum Events {
        SELECTED_PLANET = "SELECTED_PLANET",
        SERVER_TICK = "SERVER_TICK",
        SCREEN_PAIRED = "SCREEN_PAIRED",
        PLAYER_JOINED = "PLAYER_JOINED",
        LINK_CREATED = "LINK_CREATED",
        LINK_DELETED = "LINK_DELETED",
        PLAYER_ID = "PLAYER_ID",
        LINK_ID = "LINK_ID",
        FOCUS_SET = "FOCUS_SET",
}

